# Generated by Django 4.1 on 2023-02-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_members', '0002_historicalcouncilperiod_historicalcentralmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralmember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='historicalcentralmember',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='image'),
        ),
    ]
