# Generated by Django 4.1 on 2023-02-06 15:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('name', models.CharField(max_length=50, verbose_name='category name')),
                ('ordering_in_list', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ordering in list')),
            ],
            options={
                'verbose_name': 'event category',
                'verbose_name_plural': 'event categories',
                'ordering': ['ordering_in_list'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('registration_fee', models.IntegerField(default=0, verbose_name='registration fee')),
                ('date', models.DateField(verbose_name='event date')),
                ('authenticated_user_capacity', models.IntegerField(help_text='if it runs out, authenticate user use anonymous user capacity', verbose_name='authenticated user capacity')),
                ('authenticated_user_price', models.IntegerField(verbose_name='authenticated user price')),
                ('anonymous_user_capacity', models.IntegerField(verbose_name='anonymous user capacity')),
                ('anonymous_user_price', models.IntegerField(verbose_name='anonymous user price')),
                ('show_on_site', models.BooleanField(default=True, verbose_name='show on site?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.eventcategory', verbose_name='event category')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='RegisteredEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number is invalid', regex='^(\\+98|0)?9\\d{9}$')])),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid?')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event', verbose_name='event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'registered event',
                'verbose_name_plural': 'registered events',
                'unique_together': {('event', 'phone_number')},
            },
        ),
    ]
