# Generated by Django 4.1 on 2023-08-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_historicalregisteredevent_historicaleventcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='image'),
        ),
    ]
