# Generated by Django 4.1 on 2023-10-03 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_event_image_historicalevent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_events', to='events.event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='registeredevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_events', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
